const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { loadConfig, loadMappings, getConfigDir } = require('./config');

function generateNginxConfig(mapping, config) {
  const serverName = mapping.subdomain
    ? `${mapping.subdomain}.${config.cloudflare.domain}`
    : config.cloudflare.domain;

  return `# Auto-generated by cloudflare-router
# ${mapping.description || 'No description'}
# Generated: ${new Date().toISOString()}

server {
    listen ${config.nginx.listen_port};
    server_name ${serverName};

    location / {
        proxy_pass ${mapping.protocol || 'http'}://localhost:${mapping.port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Health check endpoint
    location /cf-router-health {
        return 200 '{"status":"ok","service":"${mapping.subdomain || 'root'}"}';
        add_header Content-Type application/json;
    }
}
`;
}

function generateMainNginxConfig(config, mappings) {
  const sitesDir = config.nginx.config_dir;

  let includes = '';
  mappings.filter(m => m.enabled !== false).forEach(m => {
    const configFile = path.join(sitesDir, `${m.subdomain || 'root'}.conf`);
    includes += `    include ${configFile};\n`;
  });

  return `# Auto-generated by cloudflare-router
# Main nginx configuration

events {
    worker_connections 1024;
}

http {
    # Basic settings
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    # Logging
    access_log /var/log/nginx/cloudflare-router-access.log;
    error_log /var/log/nginx/cloudflare-router-error.log;

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Include all site configs
${includes}
}
`;
}

function generateAllNginxConfigs() {
  const config = loadConfig();
  const { mappings } = loadMappings();
  const sitesDir = config.nginx.config_dir;

  if (!fs.existsSync(sitesDir)) {
    fs.mkdirSync(sitesDir, { recursive: true });
  }

  const generated = [];
  mappings.filter(m => m.enabled !== false).forEach(mapping => {
    const nginxConfig = generateNginxConfig(mapping, config);
    const filename = `${mapping.subdomain || 'root'}.conf`;
    const filepath = path.join(sitesDir, filename);
    fs.writeFileSync(filepath, nginxConfig);
    generated.push({ file: filepath, subdomain: mapping.subdomain });
  });

  const mainConfig = generateMainNginxConfig(config, mappings);
  const mainConfigPath = path.join(getConfigDir(), 'nginx', 'nginx.conf');
  fs.writeFileSync(mainConfigPath, mainConfig);

  return {
    main_config: mainConfigPath,
    site_configs: generated,
    total: generated.length
  };
}

function reloadNginx(configPath) {
  try {
    execSync(`nginx -t -c ${configPath}`, { stdio: 'pipe' });
    execSync(`nginx -s reload -c ${configPath}`, { stdio: 'pipe' });
    return { success: true, message: 'Nginx reloaded successfully' };
  } catch (error) {
    return { success: false, message: error.message };
  }
}

function getNginxStatus() {
  try {
    const output = execSync('ps aux | grep nginx | grep -v grep', { encoding: 'utf8' });
    return { running: true, processes: output.trim().split('\n').length };
  } catch {
    return { running: false, processes: 0 };
  }
}

module.exports = {
  generateNginxConfig,
  generateMainNginxConfig,
  generateAllNginxConfigs,
  reloadNginx,
  getNginxStatus
};
